### ISSUE TITLE
Suggestion: Nothing found feedback

### ISSUE THREAD

**Issue by Rico-Smit** [schalkneethling/developer-toolchest#174] opened 2022-08-16 07:08 UTC
When searching for a tool and nothing is found, there is no visible feedback. E.g. the field turning red or red border.

**Comment by schalkneethling** [comment] 2022-08-20 10:32
Thank you for reporting @Rico-Smit. This one is a Duplicate of https://github.com/schalkneethling/developer-toolchest/issues/128

**Closed** 2022-10-29 18:25 UTC
